export const actionsTypes = {
  GET_MOVIES: "GET_MOVIES",
  INCREASE_PAGE_NUMBER: "INCREASE_PAGE_NUMBER",
  DECREASE_PAGE_NUMBER: "DECREASE_PAGE_NUMBER",
  ADD_MOVIES_TO_FAVOURITE: "ADD_MOVIES_TO_FAVOURITE",
  DELETE_MOVIE: "DELETE_MOVIE",
};
